baseURL = 'https://food.richtman.au/'
languageCode = "en"

theme = "blowfish"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 999

#buildDrafts = false
#buildFuture = false

#[imaging]
#  anchor = 'Center'

#[sitemap]
#  changefreq = 'daily'
#  filename = 'sitemap.xml'
#  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
